link da aula: https://nbviewer.org/github/logictensornetworks/logictensornetworks/blob/master/tutorials/2-grounding_connectives.ipynb

In [1]:
import ltn
import numpy as np
import tensorflow as tf

Conectivos

In [2]:
Not = ltn.Wrapper_Connective(ltn.fuzzy_ops.Not_Std())
And = ltn.Wrapper_Connective(ltn.fuzzy_ops.And_Prod())
Or = ltn.Wrapper_Connective(ltn.fuzzy_ops.Or_ProbSum())
Implies = ltn.Wrapper_Connective(ltn.fuzzy_ops.Implies_Reichenbach())

In [3]:
x = ltn.Variable('x',np.random.normal(0.,1.,(10,2))) # 10 values in R²
y = ltn.Variable('y',np.random.normal(0.,2.,(5,2))) # 5 values in R²

c1 = ltn.Constant([0.5,0.0], trainable=False)
c2 = ltn.Constant([4.0,2.0], trainable=False)

Eq = ltn.Predicate.Lambda(lambda args: tf.exp(-tf.norm(args[0]-args[1],axis=1))) # predicate measuring similarity

Eq([c1,c2])

ltn.Formula(tensor=0.01775427535176277, free_vars=[])

In [9]:
tf.norm(2-1, axis=1)

InvalidArgumentError: {{function_node __wrapped__Sum_device_/job:localhost/replica:0/task:0/device:CPU:0}} Invalid reduction dimension (1 for input with 0 dimension(s) [Op:Sum]

In [5]:
Not(Eq([c1,c2]))

ltn.Formula(tensor=0.9822457432746887, free_vars=[])

In [6]:
Implies(Eq([c1,c2]), Eq([c2,c1]))

ltn.Formula(tensor=0.9824644327163696, free_vars=[])

In [7]:
# Notice the dimension of the outcome: the result is evaluated for every x.
And(Eq([x,c1]), Eq([x,c2]))

ltn.Formula(tensor=[0.00952584 0.0001903  0.00568846 0.015775   0.00895157 0.00104392
 0.01268814 0.00339151 0.01771585 0.000308  ], free_vars=['x'])

In [8]:
# Notice the dimensions of the outcome: the result is evaluated for every x and y.
# Notice also that y did not appear in the 1st argument of `Or`;
# the connective broadcasts the results of its two arguments to match.
Or(Eq([x,c1]), Eq([x,y]))

ltn.Formula(tensor=[[0.7461139  0.75401044 0.91530395 0.7761044  0.71506006]
 [0.19909666 0.11102866 0.1746522  0.17997627 0.13625187]
 [0.60098517 0.6132562  0.8044759  0.6286552  0.56819135]
 [0.29433265 0.71551764 0.45329008 0.3355314  0.26655793]
 [0.68481165 0.7133763  0.88017714 0.7068166  0.6633723 ]
 [0.5057443  0.21632905 0.31247187 0.46115217 0.2510931 ]
 [0.2905912  0.5282072  0.3599863  0.3944847  0.21728913]
 [0.47497913 0.48256195 0.67191917 0.5016668  0.43859985]
 [0.5548234  0.7142974  0.76488847 0.6022957  0.5212108 ]
 [0.16301027 0.15139967 0.23726916 0.17133644 0.13715853]], free_vars=['x', 'y'])

Quantificadores

Para todo (X) -> Forall(X)
Existe(Y)     -> Exists(y)

In [10]:
Forall = ltn.Wrapper_Quantifier(ltn.fuzzy_ops.Aggreg_pMeanError(p=2),semantics="forall")
Exists = ltn.Wrapper_Quantifier(ltn.fuzzy_ops.Aggreg_pMean(p=5),semantics="exists")

In [11]:
x = ltn.Variable('x',np.random.normal(0.,1.,(10,2))) # 10 values in R²
y = ltn.Variable('y',np.random.normal(0.,2.,(5,2))) # 5 values in R²

Eq = ltn.Predicate.Lambda(lambda args: tf.exp(-tf.norm(args[0]-args[1],axis=1))) # predicate measuring similarity

Eq([x,y])

ltn.Formula(tensor=[[0.05051445 0.02606628 0.24735689 0.06512157 0.6806783 ]
 [0.19376794 0.09482683 0.34003675 0.01591343 0.17525485]
 [0.19441836 0.03043592 0.90570784 0.03794223 0.27562663]
 [0.00860542 0.00509406 0.04569873 0.14874639 0.15405759]
 [0.13932543 0.02849137 0.7463529  0.04879234 0.39084896]
 [0.02866958 0.02202215 0.13507299 0.06168921 0.400674  ]
 [0.01925341 0.00737212 0.10308567 0.20965934 0.32227957]
 [0.08753024 0.02604836 0.46024612 0.06374279 0.6373161 ]
 [0.04164565 0.06377646 0.13197835 0.02163324 0.21484447]
 [0.17774653 0.02319394 0.6959443  0.04447243 0.26119408]], free_vars=['x', 'y'])

In [12]:
Forall(x,Eq([x,y]))

ltn.Formula(tensor=[0.09133226 0.03239125 0.31618392 0.06997782 0.32870966], free_vars=['y'])

In [13]:
Forall((x,y),Eq([x,y]))

ltn.Formula(tensor=0.15796434879302979, free_vars=[])

In [14]:
Exists((x,y),Eq([x,y]))

ltn.Formula(tensor=0.482660174369812, free_vars=[])

In [15]:
Forall(x, Exists(y, Eq([x,y])))

ltn.Formula(tensor=0.350996196269989, free_vars=[])

Eu tambem posso variar o parametro "p"

In [16]:
Forall(x,Eq([x,c1]),p=2)

ltn.Formula(tensor=0.3116726875305176, free_vars=[])

In [17]:
Forall(x,Eq([x,c1]),p=10)

ltn.Formula(tensor=0.23294514417648315, free_vars=[])

In [18]:
Exists(x,Eq([x,c1]),p=2)

ltn.Formula(tensor=0.39372286200523376, free_vars=[])

In [19]:
Exists(x,Eq([x,c1]),p=10)

ltn.Formula(tensor=0.6133526563644409, free_vars=[])